version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/devopsdb
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: node src/index.js

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
