name: CI/CD Pipeline

# Dispara o workflow sempre que houver push na branch master
on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura Docker Buildx (builder otimizado)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login no Docker Hub usando secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build e push da imagem do backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: caique07/backend:latest

      # 5️⃣ Build e push da imagem do frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: caique07/frontend:latest
